Repository carlosedp/riscvassembler, pull requests merged in 2023-01, with the labels that each got.

#18 Don't implicitly shift U-type immediates right by 12 bits
  riscvassembler/src/internal/InternalMethods.scala
  riscvassembler/test/src/RISCVAssemblerSpec.scala
  riscvassembler/test/src/internal/InternalMethodsSpec.scala
Labels: please merge

#20 Update scalatest to 3.2.15
  build.sc
Labels: please merge, dependencies

#21 Update scalafmt-core to 3.7.0
  .scalafmt.conf
Labels: please merge, dependencies

#22 Update scalafmt-core to 3.7.1
  .scalafmt.conf
Labels: dependencies
